# Generated by Django 4.2.24 on 2025-10-03 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('silla', 'Silla'), ('mesa', 'Mesa'), ('sonido', 'Sonido'), ('adorno', 'Adorno'), ('combo', 'Combo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('nombre',),
                'indexes': [models.Index(fields=['nombre'], name='servicios_s_nombre_b6403b_idx'), models.Index(fields=['tipo'], name='servicios_s_tipo_deaf72_idx'), models.Index(fields=['activo'], name='servicios_s_activo_340e8b_idx')],
            },
        ),
    ]
