# Generated by Django 4.2.24 on 2025-10-03 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=120)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ImagenSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='salones.salon')),
            ],
            options={
                'ordering': ('salon', 'orden'),
                'unique_together': {('salon', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='FechaBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_bloqueadas', to='salones.salon')),
            ],
            options={
                'verbose_name': 'Fecha bloqueada',
                'verbose_name_plural': 'Fechas bloqueadas',
                'ordering': ('-fecha',),
                'unique_together': {('salon', 'fecha')},
            },
        ),
    ]
