# Generated by Django 4.2.24 on 2025-10-03 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salones', '0001_initial'),
        ('servicios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='salones.salon')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ('-fecha_evento', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_items', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio en reserva',
                'verbose_name_plural': 'Servicios en reserva',
                'unique_together': {('reserva', 'servicio')},
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_evento'], name='reservas_re_fecha_e_70573d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
    ]
